# Generated by Django 3.1.7 on 2021-03-01 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_questions', models.TextField(verbose_name='Тип анкеты')),
                ('questions', models.TextField(verbose_name='Вопросы анкеты')),
            ],
            options={
                'verbose_name': 'Анкета',
                'db_table': 'questions',
                'managed': True,
                'unique_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='WorkersPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Должность сотрудника',
                'db_table': 'workers_position_manual',
                'managed': True,
                'unique_together': {('id', 'name_position')},
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.IntegerField(verbose_name='id наставника')),
                ('hr', models.IntegerField(verbose_name='id HR менеджера')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hermes.workersposition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'db_table': 'workers',
                'managed': True,
                'unique_together': {('id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TypesTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_test', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Типы тестов',
                'db_table': 'types_tests',
                'managed': True,
                'unique_together': {('id', 'type_test')},
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=100)),
                ('path_to_file', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Документ',
                'db_table': 'documents',
                'managed': True,
                'unique_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_test', models.TextField(verbose_name='Вопросы теста')),
                ('answers_test', models.TextField(verbose_name='Ответы теста')),
                ('true_answers_test', models.TextField(verbose_name='Правельный ответ')),
                ('type_tast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hermes.typestests')),
            ],
            options={
                'verbose_name': 'Тест',
                'db_table': 'tests',
                'managed': True,
                'unique_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='ResultsQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='Данные анкеты')),
                ('date', models.DateField(verbose_name='Дата заполнения анкеты')),
                ('type_questions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hermes.questions')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hermes.workers')),
            ],
            options={
                'verbose_name': 'Результат анкеты',
                'db_table': 'results_questions',
                'managed': True,
                'unique_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='PassingTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата прохождения теста')),
                ('number_of_attempts', models.IntegerField(verbose_name='Количество попыток прохождения теста')),
                ('status', models.BooleanField(verbose_name='Статус прохождения теста')),
                ('type_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hermes.typestests')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hermes.workers')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'db_table': 'passing_tests',
                'managed': True,
                'unique_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение для уведомления')),
                ('time_notification', models.DateTimeField(verbose_name='Время уведомления')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hermes.workers')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'db_table': 'notification',
                'managed': True,
                'unique_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение для отправки')),
                ('kod_chat', models.CharField(max_length=100)),
                ('time_message', models.DateTimeField(verbose_name='Время отправки сообщение')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipientWorkers', to='hermes.workers')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senderWorkers', to='hermes.workers')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'db_table': 'messages',
                'managed': True,
                'unique_together': {('id',)},
            },
        ),
    ]
