# Generated by Django 3.1.7 on 2021-03-01 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hermes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='typestests',
            unique_together={('type_test',), ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='workers',
            unique_together={('user',), ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='workersposition',
            unique_together={('name_position',), ('id',)},
        ),
    ]
