# Generated by Django 3.1.7 on 2021-03-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0002_auto_20210301_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='type_tast',
            new_name='type_test',
        ),
    ]
